name: Deploy
on:
  release:
    types: [published]
  push:

jobs:

  docker:
    name: Docker
    runs-on: ubuntu-latest

    strategy:
      matrix:
        credentials:
          - username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
          - username: spec-tacles
            password: ${{ secrets.GITHUB_TOKEN }}
            loginServer: docker.pkg.github.com

    steps:

    - name: Set Docker tag
      run: echo ::set-env name=DOCKER_TAG::$(echo ${{ github.ref }} | cut -d / -f 3- | sed -r 's/\/+/_/g')

    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Login to Docker
      uses: azure/container-actions/docker-login@master
      with: ${{ matrix.credentials }}

    - name: Build image
      run: docker build -t spectacles/gateway -t spectacles/gateway:$DOCKER_TAG .

    - name: Push
      run: |
        docker push spectacles/gateway
        docker push spectacles/gateway:$DOCKER_TAG

    - name: Logout of Docker
      uses: azure/container-actions/docker-logout@master
